name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.0"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
  build-docker-image:
    runs-on: ubuntu-latest
    needs: flake
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    name: Build Docker Image
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        env:
          DOCKER_USERNAME: mommde
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: echo $DOCKER_PASSWORD | docker login ghcr.io --username mommde --password-stdin

      - name: Build & Tag
        run: docker build -t ghcr.io/mommde/this-person-is-on-instagram:latest -t ghcr.io/mommde/this-person-is-on-instagram:"$GITHUB_SHA" .

      - name: Push Image to GitHub Container Registry
        run: docker push ghcr.io/mommde/this-person-is-on-instagram:latest

      - name: Push Specific Image to GitHub Container Registry
        run: docker push ghcr.io/mommde/this-person-is-on-instagram:"$GITHUB_SHA"
